/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.manager;

import ui.staff.Login;

/**
 *
 * @author nguye
 */
public class MenuQuanLy extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuQuanLy.class.getName());

    /**
     * Creates new form GiaoDienAdmin
     */
    public MenuQuanLy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnQuanlyLoaiSP = new javax.swing.JButton();
        btnQuanLySP = new javax.swing.JButton();
        btnQuanLyTheThanhVien = new javax.swing.JButton();
        btnQuanLyPhieuBanHang = new javax.swing.JButton();
        btnQuanLyNguoiDung = new javax.swing.JButton();
        btnQuanLyDoanhThu = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 53, 94));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin");

        btnQuanlyLoaiSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanlyLoaiSP.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanlyLoaiSP.setText("Quản lý loại sản phẩm");
        btnQuanlyLoaiSP.setBorderPainted(false);
        btnQuanlyLoaiSP.setContentAreaFilled(false);
        btnQuanlyLoaiSP.setFocusPainted(false);
        btnQuanlyLoaiSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanlyLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlyLoaiSPActionPerformed(evt);
            }
        });

        btnQuanLySP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLySP.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLySP.setText("Quản lý sản phẩm");
        btnQuanLySP.setBorderPainted(false);
        btnQuanLySP.setContentAreaFilled(false);
        btnQuanLySP.setFocusPainted(false);
        btnQuanLySP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLySP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySPActionPerformed(evt);
            }
        });

        btnQuanLyTheThanhVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyTheThanhVien.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyTheThanhVien.setText("Quản lý thẻ thành viên");
        btnQuanLyTheThanhVien.setBorderPainted(false);
        btnQuanLyTheThanhVien.setContentAreaFilled(false);
        btnQuanLyTheThanhVien.setFocusPainted(false);
        btnQuanLyTheThanhVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyTheThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyTheThanhVienActionPerformed(evt);
            }
        });

        btnQuanLyPhieuBanHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyPhieuBanHang.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyPhieuBanHang.setText("Quản lý phiếu bán hàng");
        btnQuanLyPhieuBanHang.setBorderPainted(false);
        btnQuanLyPhieuBanHang.setContentAreaFilled(false);
        btnQuanLyPhieuBanHang.setFocusPainted(false);
        btnQuanLyPhieuBanHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyPhieuBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyPhieuBanHangActionPerformed(evt);
            }
        });

        btnQuanLyNguoiDung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyNguoiDung.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyNguoiDung.setText("Quản lý người dùng");
        btnQuanLyNguoiDung.setBorderPainted(false);
        btnQuanLyNguoiDung.setContentAreaFilled(false);
        btnQuanLyNguoiDung.setFocusPainted(false);
        btnQuanLyNguoiDung.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNguoiDungActionPerformed(evt);
            }
        });

        btnQuanLyDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyDoanhThu.setText("Quản lý doanh thu");
        btnQuanLyDoanhThu.setBorderPainted(false);
        btnQuanLyDoanhThu.setContentAreaFilled(false);
        btnQuanLyDoanhThu.setFocusPainted(false);
        btnQuanLyDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyDoanhThuActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Đăng xuất");
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setFocusPainted(false);
        btnLogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuanLyPhieuBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnQuanlyLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnQuanLySP, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnQuanLyNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnQuanLyDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnQuanLyTheThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuanlyLoaiSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuanLySP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuanLyTheThanhVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuanLyPhieuBanHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuanLyNguoiDung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuanLyDoanhThu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        if (util.XDialog.confirm(this, "Bạn có muốn đăng xuất không?")) {
            // 1. Xóa thông tin đăng nhập cũ
            util.XAuth.logout();

            // 2. Đóng tất cả các cửa sổ đang mở (nếu cần) và giải phóng bộ nhớ
            this.dispose();

            // 3. Chạy màn hình Login trong EventQueue để đảm bảo an toàn luồng UI
            java.awt.EventQueue.invokeLater(() -> {
                new Login().setVisible(true);
            });
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnQuanLyDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyDoanhThuActionPerformed
        // TODO add your handling code here:
        if (util.XAuth.isManager()) {
            showPanel(new QLDoanhThu());
        } else {
            util.XDialog.alert(this, "Chỉ quản lý mới được xem doanh thu!");
        }
    }//GEN-LAST:event_btnQuanLyDoanhThuActionPerformed

    private void btnQuanLyNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNguoiDungActionPerformed
        // TODO add your handling code here:
        // Cách 1: Kiểm tra đúng quyền (Khuyên dùng)
        if (util.XAuth.isManager()) {
            showPanel(new QlNguoidung());
        } else {
            util.XDialog.alert(this, "Tài khoản của bạn không có quyền Quản lý!");
        }

        /* Cách 2: Nếu bạn muốn "mở khóa" luôn để sửa code cho nhanh (Chỉ dùng khi debug):
    new QlNguoidung().setVisible(true); 
         */
    }//GEN-LAST:event_btnQuanLyNguoiDungActionPerformed

    private void btnQuanLyPhieuBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyPhieuBanHangActionPerformed
        // TODO add your handling code here:
        showPanel(new Phieubanhangmoi());
    }//GEN-LAST:event_btnQuanLyPhieuBanHangActionPerformed

    private void btnQuanLyTheThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyTheThanhVienActionPerformed
        // TODO add your handling code here:
        // 1. Kiểm tra quyền hạn (Tùy chọn: Thẻ thành viên thường dành cho Quản lý hoặc Nhân viên)
        // Nếu bạn muốn chỉ Quản lý mới được vào:
        if (util.XAuth.isManager()) {
            showPanel(new QLthetv());
        } else {
            // Nếu là nhân viên vẫn cho vào thì bỏ câu lệnh if/else này
            util.XDialog.alert(this, "Chức năng này yêu cầu quyền Quản lý!");
        }
    }//GEN-LAST:event_btnQuanLyTheThanhVienActionPerformed

    private void btnQuanLySPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySPActionPerformed
        // TODO add your handling code here:
        showPanel(new QlSanpham());
    }//GEN-LAST:event_btnQuanLySPActionPerformed

    private void btnQuanlyLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlyLoaiSPActionPerformed
        // TODO add your handling code here:
        showPanel(new QlLoaiSP());
    }//GEN-LAST:event_btnQuanlyLoaiSPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuQuanLy().setVisible(true));
    }

    // Hàm hỗ trợ nhúng Form con vào jPanel2
    private void showPanel(javax.swing.JFrame form) {
        jPanel2.removeAll(); // Xóa trắng chức năng cũ đang hiển thị
        jPanel2.setLayout(new java.awt.BorderLayout()); // Chuyển layout để tự động lấp đầy
        jPanel2.add(form.getContentPane()); // Lấy "phần ruột" của form con nhét vào jPanel2
        jPanel2.revalidate(); // Tải lại cấu trúc giao diện
        jPanel2.repaint();    // Vẽ lại giao diện
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnQuanLyDoanhThu;
    private javax.swing.JButton btnQuanLyNguoiDung;
    private javax.swing.JButton btnQuanLyPhieuBanHang;
    private javax.swing.JButton btnQuanLySP;
    private javax.swing.JButton btnQuanLyTheThanhVien;
    private javax.swing.JButton btnQuanlyLoaiSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
