/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.manager;

import dao.impl.hoadonDAOImpl;
import entity.hoadon;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import util.XDialog;
import java.text.SimpleDateFormat;

/**
 *
 * @author nguye
 */
public class Phieubanhangmoi extends javax.swing.JFrame {

    hoadonDAOImpl dao = new hoadonDAOImpl(); // Khai báo để dùng chung

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Phieubanhangmoi.class.getName());
    // Khai báo Model bảng và biến tổng tiền
    private javax.swing.table.DefaultTableModel modelGioHang;
    private double tongTien = 0;
    private double tienGiamGia = 0;

    public Phieubanhangmoi() {
        initComponents();
        init(); // Khởi tạo dữ liệu
    }

    private void init() {
        setLocationRelativeTo(null);
        modelGioHang = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelGioHang.setRowCount(0);

        // 1. Mặc định chọn Chuyển khoản
        jComboBox1.setSelectedItem("chuyển khoản");

        // 2. Gọi hàm ẩn các ô tiền mặt ngay khi mở trang
        toggleTienMatFields(false);

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        jTextField3.setText(sdf.format(new java.util.Date()));
    }

    // Hàm phụ trợ để ẩn/hiện các dòng tiền mặt cho gọn code
    private void toggleTienMatFields(boolean visible) {
        jLabel11.setVisible(visible);      // Nhãn "Tiền khách đưa"
        txtTienKhachDua.setVisible(visible); // Ô nhập tiền khách đưa
        jLabel17.setVisible(visible);      // Nhãn "Tiền thối"
        jLabel15.setVisible(visible);      // Nhãn hiển thị số tiền thối
    }

    // Hàm tính toán lại tổng tiền mỗi khi có thay đổi trong bảng
    private void tinhTongTien() {
        double tongTienHang = 0;
        // Tính tổng tiền từ bảng giỏ hàng
        for (int i = 0; i < modelGioHang.getRowCount(); i++) {
            tongTienHang += Double.parseDouble(modelGioHang.getValueAt(i, 4).toString());
        }

        // Tính tổng tiền thực tế sau khi trừ Voucher
        tongTien = tongTienHang - tienGiamGia;
        if (tongTien < 0) {
            tongTien = 0;
        }

        // --- ĐIỀU CHỈNH ĐỂ HIỂN THỊ TRỐNG THAY VÌ 0 VNĐ ---
        if (tienGiamGia > 0) {
            txtMaVoucher.setText(String.format("%,.0f VNĐ", tienGiamGia));
        } else {
            txtMaVoucher.setText(""); // Nếu không có giảm giá thì để trống hoàn toàn
        }
        // ------------------------------------------------

        jLabel12.setText(String.format("%,.0f VNĐ", tongTien));

        // Cập nhật lại tiền thối (nếu có)
        txtTienKhachDuaKeyReleased(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThanhToan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnInHoaĐon = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        txtMaVoucher = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 227, 227));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));

        jLabel1.setBackground(new java.awt.Color(33, 78, 147));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 63, 121));
        jLabel1.setText("Tạo phiếu bán hàng mới");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Thông tin khách hàng");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Khách hàng:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Ngày bán:");

        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setToolTipText("");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setToolTipText("");

        jLabel6.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Thông tin sản phẩm");

        jButton1.setBackground(new java.awt.Color(65, 102, 160));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm sản phẩm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá", "Thành tiền", "Xóa"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnThanhToan.setBackground(new java.awt.Color(96, 147, 104));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(209, 98, 98));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan)
                    .addComponent(btnHuy))
                .addGap(211, 211, 211))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tổng tiền:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Giảm giá:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Phương thức:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Tiền khách đưa:");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "chuyển khoản", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText(" ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText(" ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Tiền thối:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText(" ");

        btnInHoaĐon.setBackground(new java.awt.Color(96, 147, 104));
        btnInHoaĐon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInHoaĐon.setForeground(new java.awt.Color(255, 255, 255));
        btnInHoaĐon.setText("IN HÓA ĐƠN");
        btnInHoaĐon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHoaĐonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText(" ");

        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
        });

        txtMaVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaVoucherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(492, 492, 492))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaVoucher))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)))
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnInHoaĐon, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMaVoucher))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addGap(35, 35, 35)
                .addComponent(jLabel18)
                .addGap(10, 10, 10)
                .addComponent(btnInHoaĐon)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, Short.MAX_VALUE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Hiện hộp thoại yêu cầu nhập Mã Sản Phẩm
        String maSP = javax.swing.JOptionPane.showInputDialog(this, "Nhập mã sản phẩm cần thêm:");
        if (maSP == null || maSP.trim().isEmpty()) {
            return; // Nếu người dùng bấm Hủy hoặc không nhập gì thì thoát
        }

        // Tìm sản phẩm từ Database thông qua DAO
        dao.SanPhamDAO spDAO = new dao.impl.SanPhamDAOImpl();
        entity.SanPham sp = spDAO.selectById(maSP.trim());

        if (sp != null) {
            // Hiện hộp thoại yêu cầu nhập Số Lượng (Mặc định là 1)
            String soLuongStr = javax.swing.JOptionPane.showInputDialog(this, "Nhập số lượng:", "1");
            if (soLuongStr == null) {
                return;
            }

            try {
                int soLuong = Integer.parseInt(soLuongStr);
                double thanhTien = soLuong * sp.getDonGia();

                // Đẩy dữ liệu vào jTable1 (đúng thứ tự cột bạn thiết kế)
                modelGioHang.addRow(new Object[]{
                    sp.getMaSanPham(),
                    sp.getTenSanPham(),
                    soLuong,
                    sp.getDonGia(),
                    thanhTien,
                    "Xóa" // Chữ hiển thị ở cột thao tác
                });

                tinhTongTien(); // Cập nhật lại nhãn tổng tiền ở dưới

            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Số lượng phải là số hợp lệ!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm có mã: " + maSP);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) { // Phải click đúp (2 lần) mới xóa
            int row = jTable1.getSelectedRow();
            if (row >= 0) {
                int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                        "Bạn có chắc chắn muốn xóa sản phẩm này khỏi phiếu?", "Xác nhận xóa",
                        javax.swing.JOptionPane.YES_NO_OPTION);

                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                    modelGioHang.removeRow(row);
                    tinhTongTien(); // Xóa xong phải tính lại tiền
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        // 1. Kiểm tra giỏ hàng
        if (jTable1.getRowCount() == 0) {
            util.XDialog.alert(this, "Giỏ hàng đang trống!");
            return;
        }

        try {
            // 2. Tạo Mã hóa đơn duy nhất
            String maHD = "HD" + System.currentTimeMillis() % 1000000;

            // 3. Lưu Hóa Đơn (Bảng Cha)
            entity.hoadon hd = new entity.hoadon();
            hd.setMaHoaDon(maHD);
            // Lấy mã KH từ jLabel6 nếu có, không thì mặc định KH001
            hd.setMaKhachHang(jLabel6.getText().trim().isEmpty() ? "KH001" : jLabel6.getText().trim());
            hd.setNgayLap(new java.util.Date());
            hd.setPhuongThucThanhToan(jComboBox1.getSelectedItem().toString());
            hd.setTrangThai("Đã thanh toán");
            hd.setTongTien(tongTien);
            hd.setTenDangNhap("admin");

            dao.impl.hoadonDAOImpl hdDAO = new dao.impl.hoadonDAOImpl();
            // Kiểm tra xem là .insert(hd) hay .create(hd) tùy theo file DAO của ông
            hdDAO.create(hd);

            // 4. Lưu Chi Tiết Hóa Đơn & CẬP NHẬT KHO (Bảng Con)
            dao.impl.hoadonchitietDAOImpl hdctDAO = new dao.impl.hoadonchitietDAOImpl();
            dao.SanPhamDAO spDAO = new dao.impl.SanPhamDAOImpl();

            for (int i = 0; i < modelGioHang.getRowCount(); i++) {
                String maSP = modelGioHang.getValueAt(i, 0).toString();
                int soLuongBan = Integer.parseInt(modelGioHang.getValueAt(i, 2).toString());
                double giaBan = Double.parseDouble(modelGioHang.getValueAt(i, 3).toString());

                entity.hoadonchitiet ct = new entity.hoadonchitiet();
                ct.setMaCT((int) (System.currentTimeMillis() % 100000) + i);
                ct.setMaHoaDon(maHD);
                ct.setMaSanPham(maSP);
                ct.setSoLuong(soLuongBan);
                ct.setGia(giaBan);
                hdctDAO.create(ct); // Kiểm tra lại tên hàm insert/create

                // Cập nhật kho
                entity.SanPham sp = spDAO.selectById(maSP);
                if (sp != null) {
                    sp.setSoLuongTon(sp.getSoLuongTon() - soLuongBan);
                    spDAO.update(sp);
                }
            }

            // 5. THÀNH CÔNG: Hiện nút In và báo tin
            util.XDialog.alert(this, "Thanh toán thành công! Mã HD: " + maHD);

            btnInHoaĐon.setVisible(true); // Hiện nút In ra
            btnInHoaĐon.setEnabled(true);

            // LƯU Ý: KHÔNG gọi btnHuy ở đây để giữ lại dữ liệu cho nút IN bốc đi
        } catch (Exception e) {
            util.XDialog.alert(this, "Lỗi thanh toán: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        modelGioHang.setRowCount(0);
        tinhTongTien();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        String sdt = jTextField2.getText().trim();
        if (!sdt.isEmpty()) {
            dao.KhachHangDAO khDAO = new dao.impl.KhachHangDAOImpl();
            entity.KhachHang kh = khDAO.selectByPhone(sdt); // Hàm này ông đã có trong DAO
            if (kh != null) {
                jTextField1.setText(kh.getTenKhachHang());
                jLabel6.setText(kh.getMaKhachHang()); // Lưu mã KH vào nhãn ẩn để sau này lưu hóa đơn
                util.XDialog.alert(this, "Đã tìm thấy khách hàng: " + kh.getTenKhachHang());
            } else {
                util.XDialog.alert(this, "Số điện thoại này chưa có trong hệ thống!");
            }
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtMaVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaVoucherActionPerformed
        // TODO add your handling code here:
        String maVoucher = txtMaVoucher.getText().trim();
        if (maVoucher.isEmpty()) {
            tienGiamGia = 0;
            tinhTongTien();
            return;
        }

        try {
            // Truy vấn trực tiếp từ bảng Voucher trong Database
            String sql = "SELECT Giagiam FROM Voucher WHERE MaVoucher = ?";
            // Sử dụng util.XQuery hoặc XJdbc tùy theo thư viện ông có
            java.sql.ResultSet rs = util.XJdbc.query(sql, maVoucher);

            if (rs.next()) {
                double giaTriGiam = rs.getDouble("Giagiam");
                // Theo quy ước của ông: 5.00 trong DB = 5,000 VNĐ
                tienGiamGia = giaTriGiam * 1000;

                util.XDialog.alert(this, "Áp dụng mã giảm giá thành công: " + String.format("%,.0f VNĐ", tienGiamGia));
                tinhTongTien(); // Tính lại toàn bộ tiền
            } else {
                util.XDialog.alert(this, "Mã giảm giá không tồn tại hoặc đã hết hạn!");
                tienGiamGia = 0;
                tinhTongTien();
            }
        } catch (Exception e) {
            util.XDialog.alert(this, " lỗi kiểm tra Voucher: " + e.getMessage());
        }
    }//GEN-LAST:event_txtMaVoucherActionPerformed

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        // TODO add your handling code here:
        try {
            if (txtTienKhachDua.getText().trim().isEmpty()) {
                jLabel15.setText("0 VNĐ");
                return;
            }

            double tienKhachDua = Double.parseDouble(txtTienKhachDua.getText());
            double tienThoi = tienKhachDua - tongTien; // tongTien đã được tính ở hàm tinhTongTien()

            if (tienThoi < 0) {
                jLabel15.setText("Khách đưa thiếu!");
            } else {
                jLabel15.setText(String.format("%,.0f VNĐ", tienThoi));
            }
        } catch (NumberFormatException e) {
            jLabel15.setText("Số tiền không hợp lệ!");
        }
    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void btnInHoaĐonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHoaĐonActionPerformed
        // TODO add your handling code here:
        String tenKH = jTextField1.getText().isEmpty() ? "Khách lẻ" : jTextField1.getText();
        String sdt = jTextField2.getText();
        String ngay = jTextField3.getText();
        String pthanhToan = jComboBox1.getSelectedItem().toString(); // Lấy phương thức thanh toán

        // Bắt đầu dựng nội dung hóa đơn
        StringBuilder bill = new StringBuilder();
        bill.append("        NHÀ SÁCH POLY BOOK\n");
        bill.append("   ĐC: 123 Trịnh Văn Bô, Nam Từ Liêm\n");
        bill.append("   SĐT: 0987.654.321\n");
        bill.append("------------------------------------------\n");
        bill.append(String.format(" KH: %-20s\n", tenKH));
        bill.append(String.format(" SĐT: %-20s\n", sdt));
        bill.append(String.format(" Ngày: %-20s\n", ngay));
        bill.append(String.format(" P.Thức: %-20s\n", pthanhToan)); // In phương thức thanh toán lên hóa đơn
        bill.append("------------------------------------------\n");
        bill.append(String.format("%-18s %-3s %-10s %-10s\n", "Tên SP", "SL", "Đơn giá", "Thành tiền"));

        // Lấy dữ liệu từ bảng giỏ hàng
        for (int i = 0; i < modelGioHang.getRowCount(); i++) {
            String ten = modelGioHang.getValueAt(i, 1).toString();
            String sl = modelGioHang.getValueAt(i, 2).toString();
            String gia = modelGioHang.getValueAt(i, 3).toString();
            String tt = modelGioHang.getValueAt(i, 4).toString();

            if (ten.length() > 15) {
                ten = ten.substring(0, 15) + "..";
            }
            bill.append(String.format("%-18s %-3s %-10s %-10s\n", ten, sl, gia, tt));
        }

        bill.append("------------------------------------------\n");
        bill.append(String.format(" TỔNG CỘNG:            %,.0f VNĐ\n", tongTien)); //

        // --- PHẦN ĐIỀU CHỈNH THEO Ý ÔNG ---
        if (pthanhToan.equals("Tiền mặt")) {
            try {
                // Lấy số tiền từ ô txtTienKhachDua mà ta đã tạo ở bước trước
                double khachDua = Double.parseDouble(txtTienKhachDua.getText().trim());
                double thoiLai = khachDua - tongTien;

                bill.append(String.format(" TIỀN KHÁCH ĐƯA:      %,.0f VNĐ\n", khachDua));
                bill.append(String.format(" TIỀN THỐI LẠI:       %,.0f VNĐ\n", thoiLai));
            } catch (Exception e) {
                bill.append(" TIỀN KHÁCH ĐƯA:      (Chưa nhập)\n");
            }
        }
        // Nếu là Chuyển khoản, code sẽ tự động bỏ qua phần trên và đi tiếp xuống dưới
        // ---------------------------------

        bill.append("------------------------------------------\n");
        bill.append("      CẢM ƠN QUÝ KHÁCH. HẸN GẶP LẠI!\n");

        // Hiển thị hóa đơn mô phỏng
        javax.swing.JTextArea txtArea = new javax.swing.JTextArea(bill.toString());
        txtArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));
        txtArea.setEditable(false);

        javax.swing.JOptionPane.showMessageDialog(this, new javax.swing.JScrollPane(txtArea), "HÓA ĐƠN VẬT LÝ", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Reset lại form để làm phiếu mới
        btnHuyActionPerformed(null);
        btnInHoaĐon.setVisible(false);
    }//GEN-LAST:event_btnInHoaĐonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String method = jComboBox1.getSelectedItem().toString();

        if (method.equals("Tiền mặt")) {
            toggleTienMatFields(true);  // Hiện ra nếu là tiền mặt
        } else {
            toggleTienMatFields(false); // Ẩn đi nếu là chuyển khoản
            txtTienKhachDua.setText("");
            jLabel15.setText("0 VNĐ");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Phieubanhangmoi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnInHoaĐon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtMaVoucher;
    private javax.swing.JTextField txtTienKhachDua;
    // End of variables declaration//GEN-END:variables
}
