/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.customer;

import entity.hoadon;
import entity.hoadonchitiet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Image;

/**
 *
 * @author nguye
 */
public class ThanhToan extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ThanhToan.class.getName());
    // Khai báo các DAO Implementation
    private dao.SanPhamDAO spDAO = new dao.impl.SanPhamDAOImpl();
    private dao.LoaiSPDAO loaiDAO = new dao.impl.LoaiSPDAOImpl();
    private dao.impl.hoadonchitietDAOImpl hdctDAO = new dao.impl.hoadonchitietDAOImpl();
    private dao.impl.hoadonDAOImpl hdDAO = new dao.impl.hoadonDAOImpl();
    private double tienGiam = 0; // Lưu số tiền giảm từ Voucher

    // Model để quản lý dữ liệu trên Table
    private javax.swing.table.DefaultTableModel modelSanPham;
    private javax.swing.table.DefaultTableModel modelGioHang;
    private double tongTien = 0;

    /**
     * Creates new form ThanhToan
     */
    public ThanhToan() {
        initComponents();

        init();
    }

    private void init() {
        setLocationRelativeTo(null);
        modelSanPham = (javax.swing.table.DefaultTableModel) tblDanhSach.getModel();
        modelGioHang = (javax.swing.table.DefaultTableModel) tblGioHang.getModel();
        modelGioHang.setRowCount(0);

        fillTableSanPham("");

        // Gắn sự kiện nhấn Enter cho ô mã giảm giá
        txtGiamgGia.addActionListener(evt -> txtGiamgGiaActionPerformed(evt));
    }

    private void fillTableSanPham(String keyword) {
        modelSanPham.setRowCount(0);
        try {
            java.util.List<entity.SanPham> list;
            if (keyword == null || keyword.isEmpty()) {
                list = spDAO.selectAll();
            } else {
                // Sử dụng hàm tìm kiếm theo keyword đã có trong DAO của ông
                list = spDAO.selectByKeyword(keyword);
            }

            for (entity.SanPham sp : list) {
                modelSanPham.addRow(new Object[]{
                    sp.getMaSanPham(),
                    sp.getTenSanPham(),
                    sp.getDonGia(),
                    "Chọn"
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillTableSanPham() {
        modelSanPham.setRowCount(0);
        try {
            java.util.List<entity.SanPham> list = spDAO.selectAll();
            for (entity.SanPham sp : list) {
                modelSanPham.addRow(new Object[]{
                    sp.getMaSanPham(),
                    sp.getTenSanPham(),
                    sp.getDonGia(),
                    "Chọn"
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void tinhTongTien() {
        double tongTienHang = 0;
        for (int i = 0; i < modelGioHang.getRowCount(); i++) {
            // Cột Thành tiền ở vị trí index 3
            tongTienHang += Double.parseDouble(modelGioHang.getValueAt(i, 3).toString());
        }

        // Tính tổng phải trả sau khi giảm
        tongTien = tongTienHang - tienGiam;
        if (tongTien < 0) {
            tongTien = 0;
        }

        jLabel4.setText(String.format("%,.0f VNĐ", tongTien));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        btnThanhToan1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtGiamgGia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtTim.setColumns(8);
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });
        txtTim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKeyReleased(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTim.setForeground(new java.awt.Color(12, 66, 139));
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDanhSach);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );

        jPanel2.setBackground(new java.awt.Color(34, 71, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thanh toán");

        btnBack.setBackground(new java.awt.Color(255, 0, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBack.setText("Trở lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(330, 330, 330))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Giỏ hàng");

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng", "Giá", "Thanh tiền"
            }
        ));
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblGioHang);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Giảm giá:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText(" ");

        btnHuy.setBackground(new java.awt.Color(209, 98, 98));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnThanhToan1.setBackground(new java.awt.Color(96, 147, 104));
        btnThanhToan1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThanhToan1.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan1.setText("Thanh Toán");
        btnThanhToan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToan1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tổng tiền:");

        txtGiamgGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamgGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnThanhToan1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGiamgGia, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtGiamgGia, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan1)
                    .addComponent(btnHuy))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        modelGioHang.setRowCount(0);
        tinhTongTien();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        // TODO add your handling code here:
        int row = tblGioHang.getSelectedRow();
        if (row < 0) {
            return;
        }

        Object[] options = {"Sửa số lượng", "Xóa sản phẩm", "Đóng"};
        int choice = javax.swing.JOptionPane.showOptionDialog(this,
                "Lựa chọn thao tác cho: " + modelGioHang.getValueAt(row, 0),
                "Điều chỉnh giỏ hàng",
                javax.swing.JOptionPane.YES_NO_CANCEL_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null, options, options[2]);

        if (choice == 0) { // Sửa số lượng
            String input = javax.swing.JOptionPane.showInputDialog(this, "Nhập số lượng mới:", modelGioHang.getValueAt(row, 1));
            if (input != null && !input.isEmpty()) {
                try {
                    int slMoi = Integer.parseInt(input);
                    double gia = (double) modelGioHang.getValueAt(row, 2);
                    modelGioHang.setValueAt(slMoi, row, 1);
                    modelGioHang.setValueAt(slMoi * gia, row, 3);
                    tinhTongTien();
                } catch (Exception e) {
                    util.XDialog.alert(this, "Số lượng không hợp lệ!");
                }
            }
        } else if (choice == 1) { // Xóa sản phẩm
            modelGioHang.removeRow(row);
            tinhTongTien();
        }
    }//GEN-LAST:event_tblGioHangMouseClicked

    private void btnThanhToan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToan1ActionPerformed
        // TODO add your handling code here:
        // 1. Kiểm tra giỏ hàng
        if (tblGioHang.getRowCount() == 0) {
            util.XDialog.alert(this, "Giỏ hàng đang trống! Vui lòng chọn sản phẩm.");
            return;
        }

        // 2. HIỂN THỊ MÃ QR THANH TOÁN
        try {
            // Đường dẫn đến file QR.png trong thư mục icon
            String qrPath = "src/icon/QR.png";

            // Nạp và chỉnh kích thước ảnh QR cho vừa vặn (300x300)
            ImageIcon icon = new ImageIcon(qrPath);
            Image img = icon.getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH);
            ImageIcon resizedIcon = new ImageIcon(img);

            // Tạo Panel chứa nội dung thông báo
            JPanel panel = new JPanel(new BorderLayout(10, 10));
            JLabel lblText = new JLabel("Quý khách vui lòng quét mã QR để thanh toán", SwingConstants.CENTER);
            lblText.setFont(new Font("Segoe UI", Font.BOLD, 18));
            panel.add(lblText, BorderLayout.NORTH);

            JLabel lblQR = new JLabel(resizedIcon);
            panel.add(lblQR, BorderLayout.CENTER);

            // Hiện bảng thông báo mã QR
            javax.swing.JOptionPane.showMessageDialog(this, panel, "QUY TRÌNH TỰ THANH TOÁN", javax.swing.JOptionPane.PLAIN_MESSAGE);

        } catch (Exception e) {
            System.err.println("Lỗi nạp ảnh QR: " + e.getMessage());
        }

        // 3. XỬ LÝ IN HÓA ĐƠN MÔ PHỎNG (Sau khi khách bấm OK ở bảng QR)
        StringBuilder bill = new StringBuilder();
        bill.append("        HÓA ĐƠN TỰ PHỤC VỤ (SELF-CHECKOUT)\n");
        bill.append("        NHÀ SÁCH POLY BOOK - KIOSK #01\n");
        bill.append("------------------------------------------\n");
        bill.append(String.format("%-18s %-3s %-20s\n", "Tên SP", "SL", "Thành tiền"));

        double tong = 0;
        for (int i = 0; i < tblGioHang.getRowCount(); i++) {
            String ten = tblGioHang.getValueAt(i, 0).toString(); // Tên sản phẩm
            String sl = tblGioHang.getValueAt(i, 1).toString();  // Số lượng
            // Lấy giá trị thành tiền, xóa bỏ định dạng chữ nếu có
            String ttStr = tblGioHang.getValueAt(i, 3).toString().replace(",", "").replace(" VNĐ", "");
            double tt = Double.parseDouble(ttStr);
            tong += tt;

            if (ten.length() > 15) {
                ten = ten.substring(0, 15) + "..";
            }
            bill.append(String.format("%-18s %-3s %,.0f VNĐ\n", ten, sl, tt));
        }

        bill.append("------------------------------------------\n");
        bill.append(String.format(" TỔNG CỘNG:            %,.0f VNĐ\n", tong));
        bill.append("------------------------------------------\n");
        bill.append("   CẢM ƠN QUÝ KHÁCH ĐÃ TIN TƯỞNG POLY BOOK!\n");
        bill.append("      HẸN GẶP LẠI QUÝ KHÁCH LẦN SAU.\n");

        // Tạo JTextArea để hiển thị hóa đơn với font chữ thẳng hàng
        javax.swing.JTextArea txtArea = new javax.swing.JTextArea(bill.toString());
        txtArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));
        txtArea.setEditable(false);

        // Thông báo thành công và hiện hóa đơn
        util.XDialog.alert(this, "Giao dịch thành công! Vui lòng nhận hóa đơn bên dưới.");
        javax.swing.JOptionPane.showMessageDialog(this, new javax.swing.JScrollPane(txtArea), "BIÊN LAI THANH TOÁN", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // 4. DỌN DẸP GIỎ HÀNG (Sử dụng hàm hủy có sẵn của ông)
        btnHuyActionPerformed(null);
    }//GEN-LAST:event_btnThanhToan1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Tắt form TraSP hiện tại

        // Mở lại form Menu Khách (Bạn đinew MenuKhackCheckout().setVisible(true);ều chỉnh lại tên Class Menu cho đúng nếu cần)
        new ui.customer.MenuKhackCheckout().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        // TODO add your handling code here:
        int row = tblDanhSach.getSelectedRow();
        if (row >= 0) {
            String tenSP = tblDanhSach.getValueAt(row, 1).toString();
            double gia = Double.parseDouble(tblDanhSach.getValueAt(row, 2).toString());

            String slStr = javax.swing.JOptionPane.showInputDialog(this, "Nhập số lượng cho: " + tenSP, "1");
            if (slStr != null && !slStr.isEmpty()) {
                try {
                    int sl = Integer.parseInt(slStr);
                    // tblGioHang của ông có 4 cột: Tên, SL, Giá, Thành tiền
                    modelGioHang.addRow(new Object[]{tenSP, sl, gia, sl * gia});
                    tinhTongTien();
                } catch (Exception e) {
                    util.XDialog.alert(this, "Số lượng không hợp lệ!");
                }
            }
        }
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        fillTableSanPham(txtTim.getText().trim());
    }//GEN-LAST:event_btnTimActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void txtTimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyReleased
        // TODO add your handling code here:
        fillTableSanPham(txtTim.getText().trim());
    }//GEN-LAST:event_txtTimKeyReleased

    private void txtGiamgGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamgGiaActionPerformed
        // TODO add your handling code here:
        String ma = txtGiamgGia.getText().trim();
        if (ma.isEmpty()) {
            tienGiam = 0;
            tinhTongTien();
            return;
        }
        try {
            // Truy vấn Voucher từ DB (giả sử cột Giagiam: 5.00 tương ứng 5000 VNĐ)
            String sql = "SELECT Giagiam FROM Voucher WHERE MaVoucher = ?";
            java.sql.ResultSet rs = util.XJdbc.query(sql, ma);
            if (rs.next()) {
                tienGiam = rs.getDouble("Giagiam") * 1000;
                util.XDialog.alert(this, "Áp dụng thành công mã giảm giá: " + String.format("%,.0f VNĐ", tienGiam));
                tinhTongTien();
            } else {
                util.XDialog.alert(this, "Mã giảm giá không tồn tại!");
                tienGiam = 0;
                tinhTongTien();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtGiamgGiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ThanhToan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThanhToan1;
    private javax.swing.JButton btnTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTextField txtGiamgGia;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
